name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "yubo"
database_id = "78f6cef8-b765-49b2-9298-0ef5538774d9"

[version_metadata]
binding = "CF_VERSION_METADATA"
